---
- hosts: greeters
  remote_user: vagrant
  tasks:
    - name: Create greeting container
      file:
        path: ~/greeting
        state: touch

    - name: Greet
      shell: echo "Hello World" > ~/greeting


